### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by gjergjsheldija** [FireJuun/prapare#30]
Hi
While installing the packages with `flutter pub get` I had an issue with package https://github.com/fhir-fli/fhir_auth.git which is missing. I tried finding the repo, but it does not exits.
Can i replace the missing package with the other fhir_auth packages ?

best
Gjergj

**Comment by FireJuun** [comment]
Sure. This was written before that repo had changed and been combined with all the other FHIR packages [here](https://github.com/MayJuun/fhir). Since that time, all packages have been fully published to the FHIR-FLI  group on [pub.dev](https://pub.dev/publishers/fhirfli.dev/packages)... So you should just be able to import the package by its name alone instead of by GitHub repot.

Feel free to implement that change and submit a PR if you want. Otherwise, I will soon. 

Great find, and thanks for your help

**Comment by FireJuun** [comment]
Also, for now, given the breaking changes seen by v 0.2.0 and up within this code, would suggest keeping with `fhir_auth: ^0.1.0` for now.

Will update the code in the `dev` branch to use the latest FHIR packages... But for now, an older version will likely get you up to speed

**Comment by gjergjsheldija** [comment]
Hi,

thank you for the quick reply. Managed to install the packages. 
Having the following issues when i try `flutter run` :
```
lib/services/fhir_servers/hapi_service.dart:7:17: Error: Type 'SmartFailure' not found.
  Future<Either<SmartFailure, Unit>> call(Bundle bundle) async {        
                ^^^^^^^^^^^^                                            
lib/services/fhir_servers/aidbox_service.dart:31:38: Error: The method 'accessToken' isn't defined for the class 'FhirClient'.
 - 'FhirClient' is from 'package:fhir_auth/fhir_client.dart' ('../../.pub-cache/hosted/pub.dartlang.org/fhir_auth-0.0.1/lib/fhir_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'accessToken'.
          final token = await client.accessToken();                     
                                     ^^^^^^^^^^^                        
lib/services/fhir_servers/hapi_service.dart:16:19: Error: The getter 'SmartFailure' isn't defined for the class 'HapiService'.
 - 'HapiService' is from 'package:prapare/services/fhir_servers/hapi_service.dart' ('lib/services/fhir_servers/hapi_service.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'SmartFailure'.
      (l) => left(SmartFailure.unknownFailure(failedValue: l)),         
                  ^^^^^^^^^^^^                                          
lib/services/fhir_servers/mihin_service.dart:66:44: Error: The method 'accessToken' isn't defined for the class 'FhirClient'.
 - 'FhirClient' is from 'package:fhir_auth/fhir_client.dart' ('../../.pub-cache/hosted/pub.dartlang.org/fhir_auth-0.0.1/lib/fhir_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'accessToken'.
                    'Bearer ${await client.accessToken()}'              
                                           ^^^^^^^^^^^                  
lib/services/service_call.dart:103:42: Error: The method 'errorMessage' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.                                        
Try correcting the name to the name of an existing method, or defining a method named 'errorMessage'.
              (l) => RemoteState.error(l.errorMessage()),     
```
output of flutter -version : 
```
❯ flutter --version
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (6 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
```
contents of pubspec.yaml : 
```
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fhir_auth: 0.0.1
  cupertino_icons: ^1.0.0
  fhir: ^0.0.13
  fhir_at_rest: ^0.0.10
  fhir_db: ^0.0.4
  flutter_launcher_icons: ^0.8.1
  flutter_multi_formatter: ^1.3.0
  flutter_sheet_localization: ^2.0.1
  flutter_svg: ^0.19.1
  get: ^3.23.1
  get_storage: ^1.3.2
  http: ^0.12.2
  introduction_screen: ^1.0.9
  money2: ^1.4.3
  translator: ^0.1.5
  url_launcher: ^5.7.10
  validators: ^2.0.1
  remote_state: ^1.5.0
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  flutter_sheet_localization_generator: ^2.0.0
  freezed: ^0.12.2
```

From what i can get from looking at the source code, those methods seems to be missing.
